### ISSUE TITLE
CKAN incorrect compatible information

### ISSUE THREAD

**Issue by Artemonim** [KSPSnark/AntennaSleep#1]
After update to 1.5.1 CKAN says, that mod can't work with 1.4.* KSP versions.
That's a mistake, right?

![2018-10-20 13-48-26](https://user-images.githubusercontent.com/36363466/47254749-f5cacd80-d46e-11e8-9715-314e2379990c.png)

**Comment by KSPSnark** [comment]
Yep, it should work just fine.  CKAN's got it wrong.

(I don't maintain any of the CKAN data myself-- the complete extent of my CKAN involvement is to check the little checkbox on SpaceDock "do you want this mod to be on CKAN?" when initially creating the mod.)

AntennaSleep code hasn't changed in quite a long time (it's a very small/simple mod, so it uses only a tiny slice of KSP's API and there's not much to get broken when KSP does an update), so the current AntennaSleep should work fine on any KSP version going back to KSP 1.2.
